baseurl = "https://simeonivanov.org/"
title = "DevOps - Simeon Ivanov"
header = "Simeon Ivanov"
theme = "rusty-typewriter"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Simeon Ivanov"
keywords = "blog,developer,devops,security"
avatarurl = "images/avatar.png"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2024

enableTwemoji = true

colorScheme = "dark"
hidecolorschemetoggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 1
url = "mailto:s.ivanov1994@proton.me"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/simeonivanov1994/"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 3
url = "https://github.com/sivanov1994"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "/posts/"
[[menu.main]]
name = "About"
weight = 2
url = "/about/"


# rusty-typewriter theme settings
[params.rtwt]
sidePane = true
countPageItems = 7
searchPath = 'search'

[params.rtwt.home]
showBio = true
showAuthorImg = true
sidePaneTags = true
showFeatured = true
showRecent = true
hideRecentWhenFeatured = true
countRecent = 3

[params.rtwt.side.home]
sidePaneSticky = false
taxonomies = ['tags']
countTaxonomy = 5

[params.rtwt.side.single]
sidePaneSticky = false
showDetails = true
showTableOfContents = true
showAttachments = false
showRelated = true
countRelated = 5

[outputFormats]
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[mediaTypes]
[mediaTypes."application/json"]
suffixes = ["json"]

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
